apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debate.fullname" . }}
  labels:
    {{- include "debate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "debate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "debate.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "debate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probe.enabled }}
          livenessProbe:
            {{- toYaml .Values.probe.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probe.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: debate-secret
                  key: openai-key
            - name: DEBATE_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: debate-config
                  key: debate-postgres-host
            - name: DEBATE_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: debate-config
                  key: debate-postgres-port
            - name: DEBATE_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: debate-config
                  key: debate-postgres-user
            - name: DEBATE_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: debate-config
                  key: debate-redis-host
            - name: DEBATE_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: debate-config
                  key: debate-redis-port
            - name: DEBATE_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: debate-secret
                  key: debate-redis-password
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
