spring:
    profiles:
      default: local

    servlet:
      multipart:
        max-request-size: 100MB
        max-file-size: 10MB

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui
    enabled: true