spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${AUTH_POSTGRES_HOST}:${AUTH_POSTGRES_PORT}/auth
    username: ${AUTH_POSTGRES_USER}
    password: ${AUTH_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      port: ${AUTH_REDIS_PORT}
      host: ${AUTH_REDIS_HOST}

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                scope:
                - email
                - name
#            apple:
#                client-id: ${APPLE_CLIENT_ID}
#                client-secret: ${APPLE_CLIENT_SECRET}
#                scope:
#                - email
#                - name

jwt:
  secret: ${JWT_SECRET}
  access_expiration: ${ACCESS_EXPIRATION}
  refresh_expiration: ${REFRESH_EXPIRATION}

server:
  port: 8080