spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/auth
    username: auth
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      port: 6379
      host: 0.0.0.0

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

jwt:
  secret: "test_JWT_secret"
  access_expiration: 3600000
  refresh_expiration: 86400000

server:
  port: 8080


