spring:
  application:
    name: community
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    hikari:
      maximumPoolSize: 4
    url: jdbc:postgresql://localhost:5432/community
    username: test
    password: test
    driverClassName: org.postgresql.Driver
