spring:
  application:
    name: community

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/community
    username: community
    password: 1234
    driver-class-name: org.postgresql.Driver


  data:
    redis:
      port: 6379
      host: localhost

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

server:
  port: 8083