spring:
  application:
    name: community

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  datasource:
    url: jdbc:postgresql://${COMMUNITY_POSTGRES_HOST}:${COMMUNITY_POSTGRES_PORT}/community
    username: ${COMMUNITY_POSTGRES_USER}
    password: ${COMMUNITY_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver


  data:
    redis:
      port: ${COMMUNITY_REDIS_PORT}
      host: ${COMMUNITY_REDIS_HOST}

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

server:
  port: 8083