apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-server.fullname" . }}
  labels:
    {{- include "auth-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.probe.enabled }}
          livenessProbe:
            {{- toYaml .Values.probe.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probe.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: AUTH_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: redis-password
            - name: AUTH_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: redis-host
            - name: AUTH_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: redis-port
            - name: AUTH_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: postgres-host
            - name: AUTH_POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: postgres-port
            - name: AUTH_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: postgres-user
            - name: AUTH_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: jwt-secret
            - name: ACCESS_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: access-expiration
            - name: REFRESH_EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: auth-server-configmap
                  key: access-expiration
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: google-client-id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: google-client-secret
            - name: APPLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: apple-client-id
            - name: APPLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: apple-client-secret
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: aws-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: aws-secret-key
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: aws-s3-bucket
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: auth-server-secret
                  key: aws-s3-region
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
