version: "3"

services:

  redis:
    container_name: redis-auth
    hostname: redis-auth
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
      TZ: "Asia/Seoul"
    networks:
      - auth

  postgres:
    container_name: postgres-auth
    hostname: postgres-auth
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: 1234
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - auth

  application:
    container_name: auth-service
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      TZ: "Asia/Seoul"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/auth
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      JWT_SECRET: "test_JWT_secret"
    depends_on:
      - redis-auth
      - postgres-auth
    networks:
      - auth

networks:
  auth:
    driver: bridge