version: "3"

services:

  redis:
    container_name: redis-auth
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
      TZ: "Asia/Seoul"

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: 1234
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data