version: "3"

services:
  postgres:
    container_name: postgres-community
    hostname: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: community
      POSTGRES_USER: community
      POSTGRES_PASSWORD: 1234
      PGPORT: 5432
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-community
    hostname: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    environment:
      TZ: "Asia/Seoul"
