version: "3"

services:
  postgres:
    container_name: postgres_debate
    hostname: postgres
    image: postgres:latest
    ports:
      - "5433:5433"
    restart: always
    environment:
      POSTGRES_DB: debate
      POSTGRES_USER: debate
      POSTGRES_PASSWORD: 1234
      PGPORT: 5433
      TZ: "Asia/Seoul"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
