spring:
  application:
    name: composite-service

  data:
    redis:
      port: 6379
      host: redis

jwt:
  secret: "test_JWT_secret"

# at docker compose
address:
  auth: "http://auth-service:8080"
  debate: "http://debate-service:8082"
  magician: "http://magician:8000"
  community: "http://community-service:8083"

server:
  port: 8081