spring:
  application:
    name: composite-service

  data:
    redis:
      port: 6379
      host: redis

jwt:
  secret: "test_JWT_secret"

# at docker compose
address:
  auth: "http://auth-service:8080"
  debate: "http://debate-service:8082"
  magician: "http://magician:8000"
  community: "http://community-service:8083"

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack:
      auto: false

server:
  port: 8081