spring:
  application:
    name: composite-service

  data:
    redis:
      port: ${COMPOSITE_REDIS_PORT}
      host: ${COMPOSITE_REDIS_HOST}

jwt:
  secret: ${JWT_SECRET}

# at K8s
address:
  auth: ${ADDRESS_AUTH}
  debate: ${ADDRESS_DEBATE}
  magician: ${ADDRESS_MAGICIAN}
  community: ${ADDRESS_COMMUNITY}

server:
  port: 8081

