spring:
  application:
    name: debate

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/debate
    username: debate
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8082

openai:
  api:
    key: ${OPENAI_KEY}
    url: https://api.openai.com/v1/chat/completions