spring:
  application:
    name: debate

  datasource:
    url: jdbc:postgresql://${DEBATE_POSTGRES_HOST}:${DEBATE_POSTGRES_PORT}/debate
    username: ${DEBATE_POSTGRES_USER}
    password: ${DEBATE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      port: ${DEBATE_REDIS_PORT}
      host: ${DEBATE_REDIS_PORT}

server:
  port: 8082

openai:
  api:
    key: ${OPENAI_KEY}
    url: https://api.openai.com/v1/chat/completions