version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=chat_db

  application:
    build: .
    depends_on:
      - mongodb
    restart: always
    container_name: magician
    ports:
      - "8000:8000"
    environment:
      OPENAI_KEY: ""
      MAGICIAN_MONGO_USERNAME: root
      MAGICIAN_MONGO_PASSWORD: 1234
      MAGICIAN_MONGO_PORT: 27017
      MAGICIAN_MONGO_HOST: mongodb

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper
