version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongo-magician
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=chat_db
    networks:
      - magician

  application:
    build: .
    depends_on:
      - mongodb
    restart: always
    container_name: magician
    ports:
      - "8000:8000"
    environment:
      OPENAI_KEY: ""
      MAGICIAN_MONGO_USERNAME: root
      MAGICIAN_MONGO_PASSWORD: 1234
      MAGICIAN_MONGO_PORT: 27017
      MAGICIAN_MONGO_HOST: mongo-magician
    networks:
      - magician

networks:
  magician:
    driver: bridge
