name: auth-server test

on:
  pull_request:
    branches: [ "back-dev" ]
  push:
    branches: [ "back-dev" ]
    
env:
  working-directory: ./auth-server

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # 체크아웃
    - name: Checkout Source
      uses: action/checkout@4
      
    # 자바 17 환경설정
    - name: Setup Java17
      uses: action/setup-java@4.2.1
      with:
        java-version: 17

    # 테스트 환경설정
    - name: Setup Test inv
      run: docker-compose -f auth-service-test-docker-compose.yml up
      working-directory: ${{ env.working-directory }}
    
    # Gradle 실행권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}

    # Spring boot application 테스트 실행
    - name: Test with gradle
      run: ./gradlew test
      working-directory: ${{ env.working-directory }}
