name: auth-server test

# back-dev, back 하위 브랜치에 풀리퀘, 푸시가 일어날때 auth-server 하위에 변경이 있다면 실행.
on:
  pull_request:
    branches: 
    - back-dev
    - back/*
    paths: 'auth-service/**'
  push:
    branches: 
    - back-dev
    - back/*
    paths: 'auth-service/**'
    
env:
  working-directory: ./auth-service

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:

    # 체크아웃
    - name: Checkout Source
      uses: action/checkout@4
      
    # 자바 17 환경설정
    - name: Setup Java17
      uses: action/setup-java@4.2.1
      with:
        java-version: 17

    # 테스트 환경설정
    - name: Setup Test inv
      run: docker-compose -f auth-service-test-docker-compose.yml up
      working-directory: ${{ env.working-directory }}
    
    # Gradle 실행권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}

    # Spring boot application 테스트 실행
    - name: Test with gradle
      run: ./gradlew test
      working-directory: ${{ env.working-directory }}

    # 테스트 결과를 PR에 코멘트로 등록합니다
    - name: Add Test Comment 
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: '**/build/test-results/test/TEST-*.xml'
