name: Composite-Server Test

# back-dev, back 하위 브랜치에 풀리퀘, 푸시가 일어날때 auth-server 하위에 변경이 있다면 실행.
on:
  pull_request:
    branches: 
    - back-dev
    - back/**
    paths: 'composite-service/**'
  push:
    branches: 
    - back-dev
    - back/**
    paths: 'composite-service/**'
    
env:
  working-directory: ./composite-service

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
    
      kafka:
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        env:
          KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
          # 여기다가 토픽 확장하기.
          KAFKA_CREATE_TOPICS: "test:1:1, magician:1:1"
          KAFKA_ZOOKEEPER_CONNECT: 0.0.0.0:2181

    steps:
    # 체크아웃
    - name: Checkout Source
      uses: actions/checkout@v4
      
    # 자바 17 환경설정
    - name: Setup Java17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
    
    # Gradle 실행권한 부여
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
      working-directory: ${{ env.working-directory }}

    # Spring boot application 테스트 실행
    - name: Test with gradle
      run: ./gradlew test
      working-directory: ${{ env.working-directory }}
