name: Magician-Server Deploy

on:
  pull_request:
    branches: [ "main" ]
    paths:
    - "magician/**"
env:
  working-directory: ./magician
  image-name: magician-server
  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
  MAGICIAN_MONGO_HOST: 0.0.0.0
  MAGICIAN_MONGO_PASSWORD: 1234
  MAGICIAN_MONGO_PORT: 27017
  MAGICIAN_MONGO_USERNAME: root

jobs:
  test-build:
    name: Test-Build
    runs-on: ubuntu-latest
  
    steps:
      # 체크아웃
      - name: Checkout Source
        uses: actions/checkout@v4

      # 몽고디비 설정
      - name: mongo-action
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-db: 'chat_db'
          mongodb-username: 'root'
          mongodb-password: 1234
          
      # 파이썬 환경설정
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
      
      # requirements 다운
      - name: Install requirements.txt
        run: pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}
      
      # 백그라운드 어플리케이션 실행
      - name: Start application
        run: python main.py &
        working-directory: ${{ env.working-directory }}

      # 테스트 실행
      - name: Test with pytest
        run: pytest
        working-directory: ${{ env.working-directory }}
      
      # docker image 빌드
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image-name }} .
        working-directory: ${{ env.working-directory }}
        
      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.image-name }}
        working-directory: ${{ env.working-directory }}
