name: magician-server test

on:
  pull_request:
    branches: 
    - back-dev
    - back/*
    paths: 'magician/**'
  push:
    branches: 
    - back-dev
    - back/*
    paths: 'magician/**'
env:
  working-directory: ./magician
  MAGICIAN_MONGO_HOST: 127.0.0.1
  MAGICIAN_MONGO_PASSWORD: 1234
  MAGICIAN_MONGO_PORT: 6379
  MAGICIAN_MONGO_USERNAME: root
  OPENAI_KEY: ${{ secret.OPENAI_KEY }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    # 체크아웃
    - name: Checkout Source
      uses: action/checkout@4.1.2

    # 파이썬 환경설정
    - name: Setup Python
      uses: action/setup-python@5
      with:
        python-version: 3.11.8

    # 테스트 환경설정
    - name: Setup Test inv
      run: docker-compose -f magician-test-docker-compose.yml up -d
      working-directory: ${{ env.working-directory }}
      
    # requirements 다운
    - name: Install requirements.txt
      run: pip install -r requirements.txt

    # 테스트 실행
    - name: Test with pytest
      run: | 
        pip install pytest pytest-cov
        pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
