name: magician-server test

on:
  pull_request:
    branches: ["back-dev"]
  push:
    branches: ["back-dev"]
env:
  working-directory: ./magician
  image-name: magician-server

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # 체크아웃
    - name: Checkout Source
      uses: action/checkout@4.1.2

    # 파이썬 환경설정
    - name: Setup Python
      uses: action/setup-python@5
      with:
        python-version: 3.11.8

    # 테스트 환경설정
    - name: Setup Test inv
      run: docker-compose -f magician-test-docker-compose.yml up
      working-directory: ${{ env.working-directory }}
      
    # requirements 다운
    - name: Install requirements.txt
      run: pip install -r requirements.txt

    # 테스트 실행
    - name: Init Pytest
      run: pytest
